# Generated by Django 3.2 on 2021-04-17 17:06

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='موقیع مکانی'),
        ),
    ]
