# Generated by Django 3.2 on 2021-04-21 09:58

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesetting_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='تصویر map'),
        ),
    ]
